In [1]:
import numpy as np
import matplotlib.pyplot as plt
# import pandas as pd


In [ ]:
# Q1(a)

X = np.array([[0, 2], [1, 0], [3, 4]], dtype=float)

print("X: ", X)

print("X.T @ X: ", X.T @ X)

# Eigendecomposition of X.T @ X
eigenvalues, eigenvectors = np.linalg.eig(X.T @ X)

print("Eigenvalues: ", eigenvalues)
print("Eigenvectors: ", eigenvectors)

# SVD of X:
U, S, V = np.linalg.svd(X)

print("U: ", U)
print("S: ", S)
print("V: ", V)


X:  [[0. 2.]
 [1. 0.]
 [3. 4.]]
X.T @ X:  [[10. 12.]
 [12. 20.]]
Eigenvalues:  [ 2. 28.]
Eigenvectors:  [[-0.83205029 -0.5547002 ]
 [ 0.5547002  -0.83205029]]
Manual Eigenvectors:  [[ 0.83205029  0.5547002 ]
 [-0.5547002   0.83205029]]
U:  [[-0.31448545  0.78446454 -0.53452248]
 [-0.10482848 -0.58834841 -0.80178373]
 [-0.94345635 -0.19611614  0.26726124]]
S:  [5.29150262 1.41421356]
V:  [[-0.5547002  -0.83205029]
 [-0.83205029  0.5547002 ]]


In [ ]:
# Q1(b)

# Power Method for A = X @ X.T
A = X @ X.T

x0 = np.array([1, 0, 0])

x1 = A @ x0
print("x1: ", x1)
print("x1 norm: ", np.linalg.norm(x1))
x1 = x1 / np.linalg.norm(x1)
print("normalized x1: ", x1)

x2 = A @ x1
print("x2: ", x2)
print("x2 norm: ", np.linalg.norm(x2))
x2 = x2 / np.linalg.norm(x2)
print("normalized x2: ", x2)

# Approximate Eigenvalue for A

lambda1 = x2.T @ A @ x2 / (x2.T @ x2)
print("Approximate Eigenvalue for A: ", lambda1)


x1:  [4. 0. 8.]
x1 norm:  8.94427190999916
normalized x1:  [0.4472136  0.         0.89442719]
x2:  [ 8.94427191  2.68328157 25.93838854]
x2 norm:  27.568097504180447
normalized x2:  [0.32444284 0.09733285 0.94088424]
Approximate Eigenvalue for A:  27.995789473684212
[ 54.4  18.  162.8]
